#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Laine Jones
"""
Generate src/p2c.S: planar -> chunky, 8 planes, 32 pixels per pass, for the
68020+. Run:  python3 tools/gen_p2c.py > src/p2c.S   (it self-tests first)

Eight plane longs sit in d0-d7 (row i = plane 7-i) and go through an 8x8
bit-matrix transpose (three delta-swap stages, on all four bytes at once)
and a 4x4 byte transpose per half (two more), which leaves eight longs of
four chunky pixels each. A delta swap needs a scratch register, and its
mask is much cheaper from a register than as an immediate - so two data
registers are kept free (d7 scratch, d6 mask), two rows are always parked
in a3/a5, and `exg` rotates which.
"""
import random
import sys

rows = {}          # row -> register
temp = None
code = []
ops = []           # simulation: (op, args)


def emit(text, op=None):
    code.append("        " + text)
    if op:
        ops.append(op)


def park(need):
    """make sure every row in `need` is in a data register"""
    for r in need:
        areg = rows[r]
        if areg[0] == 'a':
            victim = next(v for v in range(8) if v not in need and rows[v][0] == 'd')
            reg = rows[victim]
            emit("exg     %s,%s" % (reg, areg), ('exg', reg, areg))
            rows[r], rows[victim] = reg, areg


def swap(i, j, shift, mask):
    park((i, j))
    ri, rj, t = rows[i], rows[j], temp
    emit("move.l  %s,%s" % (rj, t), ('move', rj, t))
    if shift == 16:
        emit("swap    %s" % t, ('swap', t))
    else:
        emit("lsr.l   #%d,%s" % (shift, t), ('lsr', shift, t))
    emit("eor.l   %s,%s" % (ri, t), ('eor', ri, t))
    emit("and.l   d6,%s" % t, ('andr', 'd6', t))
    emit("eor.l   %s,%s" % (t, ri), ('eor', t, ri))
    if shift == 16:
        emit("swap    %s" % t, ('swap', t))
    else:
        emit("lsl.l   #%d,%s" % (shift, t), ('lsl', shift, t))
    emit("eor.l   %s,%s" % (t, rj), ('eor', t, rj))


def build():
    global temp
    for i in range(8):
        rows[i] = 'd%d' % i
    emit("movea.l d7,a3", ('move', 'd7', 'a3'))
    emit("movea.l d6,a5", ('move', 'd6', 'a5'))
    rows[7] = 'a3'
    rows[6] = 'a5'
    temp = 'd7'
    stages = [
        (4, 0x0f0f0f0f, [(0, 4), (1, 5), (2, 6), (3, 7)]),
        (2, 0x33333333, [(0, 2), (1, 3), (4, 6), (5, 7)]),
        (1, 0x55555555, [(0, 1), (2, 3), (4, 5), (6, 7)]),
        (16, 0x0000ffff, [(0, 2), (1, 3), (4, 6), (5, 7)]),
        (8, 0x00ff00ff, [(0, 1), (2, 3), (4, 5), (6, 7)]),
    ]
    for shift, mask, pairs in stages:
        emit("move.l  #0x%08x,d6" % mask, ('movei', mask, 'd6'))
        for i, j in pairs:
            swap(i, j, shift, mask)


def simulate(planes):
    """planes[p] = 32-bit value of plane p; returns the register file"""
    reg = {'d%d' % i: planes[7 - i] for i in range(8)}
    reg['a3'] = reg['a5'] = 0
    M = 0xffffffff
    for op in ops:
        if op[0] == 'move':
            reg[op[2]] = reg[op[1]]
        elif op[0] == 'exg':
            reg[op[1]], reg[op[2]] = reg[op[2]], reg[op[1]]
        elif op[0] == 'swap':
            v = reg[op[1]]
            reg[op[1]] = ((v << 16) | (v >> 16)) & M
        elif op[0] == 'lsr':
            reg[op[2]] = reg[op[2]] >> op[1]
        elif op[0] == 'lsl':
            reg[op[2]] = (reg[op[2]] << op[1]) & M
        elif op[0] == 'eor':
            reg[op[2]] ^= reg[op[1]]
        elif op[0] == 'andr':
            reg[op[2]] &= reg[op[1]]
        elif op[0] == 'movei':
            reg[op[2]] = op[1]
    return reg


def selftest():
    """returns the store order: for output long m, the row holding it"""
    order = None
    for _ in range(200):
        planes = [random.getrandbits(32) for _ in range(8)]
        chunky = [sum(((planes[p] >> (31 - px)) & 1) << p for p in range(8)) for px in range(32)]
        want = [(chunky[4 * m] << 24) | (chunky[4 * m + 1] << 16) | (chunky[4 * m + 2] << 8) |
                chunky[4 * m + 3] for m in range(8)]
        reg = simulate(planes)
        got = {r: reg[rows[r]] for r in range(8)}
        this = []
        for m in range(8):
            holders = [r for r in range(8) if got[r] == want[m]]
            assert holders, "no row holds output long %d" % m
            this.append(holders[0])
        if order is None:
            order = this
        # random data: the mapping must be the same every time
        assert sorted(this) == list(range(8)) and this == order, (this, order)
    return order


build()
order = selftest()

print("""| SPDX-License-Identifier: GPL-3.0-only
| Copyright (C) 2026 Laine Jones
| p2c.S - GENERATED by tools/gen_p2c.py (self-tested there): do not edit.
|
| void p2c8(const UBYTE **planes, ULONG *out, ULONG groups)
|
| planes[0..7] point at the first byte to convert in planes 0..7 (all eight
| must be readable: pass a row of zeros or ones for a missing plane); each
| group turns 32 pixels - one long per plane - into 32 chunky bytes at out.

        .text
        .globl  _p2c8
_p2c8:
        movem.l d2-d7/a2-a6,-(sp)
        movea.l 48(sp),a2
        movea.l 52(sp),a1
        move.l  56(sp),d0
        lsl.l   #2,d0
        movea.l d0,a6                   | end offset
        suba.l  a4,a4                   | offset into the planes
        cmpa.l  a6,a4
        beq     9f
1:""")
for i in range(8):
    print("        movea.l %d(a2),a3" % (4 * (7 - i)))
    print("        move.l  (a3,a4.l),d%d" % i)
print("\n".join(code))
for m in range(8):
    print("        move.l  %s,(a1)+" % rows[order[m]])
print("""        addq.l  #4,a4
        cmpa.l  a6,a4
        bne     1b
9:      movem.l (sp)+,d2-d7/a2-a6
        rts""")
print("generated: %d instructions per 32 pixels, store order %s" % (len(code) + 16 + 8 + 3, order),
      file=sys.stderr)
